import turtle
pig = turtle.Turtle()
pig.shape("turtle")
pig.speed(1)
# draw the pink triangle on top
pig.fillcolor("pink")
pig.begin_fill()
pig.forward(100)
pig.left(120)
pig.forward(100)
pig.left(120)
pig.forward(100)
pig.end_fill()
# draw the green triangle
pig.fillcolor("green")
pig.begin_fill()
pig.forward(100)
pig.left(120)
pig.forward(100)
pig.left(120)
pig.forward(100)
pig.end_fill()
# draw the black triangle
pig.fillcolor("black")
pig.begin_fill()
pig.right(120)
pig.forward(100)
pig.right(120)
pig.forward(100)
pig.end_fill()
# draw the pink triangle
pig.fillcolor("red")
pig.begin_fill()
pig.left(120)
pig.forward(100)
pig.left(120)
pig.forward(100)
pig.end_fill()
